modLoader="javafml"
loaderVersion="[46,)"
license="MIT"

[[mods]]
modId="reeses_sodium_options"
version="${version}"
displayName="TexTrue's Rubidium Options"
displayURL="https://github.com/ThinkingStudios/ReesesSodiumOptions-Forge"
logoFile= "icon.png"
credits="FlashyReese"
authors="TexTrue, TexTrueStudio"
description='''
Replaces Rubidium Options Screen
'''

[[dependencies.reeses_sodium_options]]
modId = "forge"
mandatory = true
versionRange = "[46,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.reeses_sodium_options]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.reeses_sodium_options]]
modId = "rubidium"
mandatory = true
versionRange = "[0.6.5,]"
ordering = "NONE"
side = "CLIENT"

# Kir-Antipov/mc-publish
[mc-publish]
loaders=["forge", "neoforge"]