modLoader="javafml"
loaderVersion="[36,)"
license="MIT"

[[mods]]
modId="reeses_sodium_options"
version="${version}"
displayName="TexTrue's Rubidium Options"
logoFile= "icon.png"
description='''
Replaces Sodium-ForgePort's Options Screen
'''
credits="FlashyReese,TexTrue"
authors="TexTrueStudio"