modLoader="javafml"
loaderVersion="[39,)"
license="MIT"

[[mods]]
modId="reeses_sodium_options"
version="${version}"
displayName="Reese's Sodium Options-Forge"
logoFile="icon.png"
description='''
Replaces Sodium-ForgePort's Options Screen
'''
credits="FlashyReese,TexTrue"
authors="TexTrueStudio"