modLoader="javafml"
loaderVersion="[44,)"
license="MIT"

[[mods]]
modId="reeses_sodium_options"
version="${version}"
displayName="TexTrue's Rubidium Options"
logoFile= "icon.png"
credits="FlashyReese"
authors="TexTrue, TexTrueStudio"
description='''
Replaces Sodium-ForgePort's Options Screen
'''


[[dependencies.reeses_sodium_options]]
modId = "forge"
mandatory = true
versionRange = "[44,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.reeses_sodium_options]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.3,]"
ordering = "NONE"
side = "BOTH"

[[dependencies.reeses_sodium_options]]
modId = "rubidium"
mandatory = true
versionRange = "[0.6,)"
ordering = "NONE"
side = "CLIENT"