name: Publish Release

on: [workflow_dispatch] # Manual trigger

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Get previous tag
        run: echo "previous_tag=$(git rev-parse $(git describe --tags --abbrev=0 --exclude *-dev) 2>/dev/null || echo '')" >> $GITHUB_ENV

      - name: Publish to Modrinth & CurseForge
        uses: Kir-Antipov/mc-publish@v3
        with:
          modrinth-id: nm57myYP
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          curseforge-id: 663125
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}

          github-token: ${{ secrets.GITHUB_TOKEN }}

          name: 1.0.0+23H1.1+Rb0.6.5-mc1.20.1
          version: 1.0.0+23H1.1+Rb0.6.5-mc1.20.1
          changelog-file: changelog.md

          version-type: release
          loaders: |
            forge
            neoforge

          game-version-filter: releases
          game-versions: |
            [1.20,1.20.1]

          dependencies: |
            rubidium@0.6.5(required)
            rubidium-extra(recommended)
            oculus(recommended)

          java: |
            17
            18